language: scala
scala:
  - 2.12.1
  - 2.11.8
  - 2.10.6
env:
- JDK=oraclejdk8
- JDK=openjdk8
- JDK=oraclejdk7
- JDK=openjdk7
- JDK=oraclejdk6
- JDK=openjdk6
addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - scala-logging
  hostname: scala-logging
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
sudo: required
before_script:
  - jdk_switcher use $JDK
matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.0
      env: JDK=oraclejdk7
    - scala: 2.12.0
      env: JDK=openjdk7
    - scala: 2.12.0
      env: JDK=oraclejdk6
    - scala: 2.12.0
      env: JDK=openjdk6
